name: retiming
channels:
  - pytorch
  - defaults
dependencies:
- python=3.8
- pytorch=1.4.0
- pip:
  - dominate==2.4.0
  - torchvision==0.5.0
  - Pillow>=6.1.0
  - numpy==1.19.2
  - visdom==0.1.8
  - opencv-python>=4.2.0
  - matplotlib

